[package]
name = "rurt"
version = "0.1.0"
edition = "2021"
default-run = "browser"

[dependencies]
anyhow = "1"
clap = { version = "4", features = ["derive"] }
dirs = "6"
ignore = "0.4"
open = "5"
skim = "0.15"
tuikit= "0.5"
once_cell= "1.20"

[dependencies.lscolors]
version = "0.20"
default-features = false
features = ["ansi_term"]
