[package]
name = "rurt"
version = "0.1.0"
edition = "2021"
default-run = "browser"

[dependencies]
anyhow = "1"
clap = { version = "4", features = ["derive"] }
dirs = "6"
ignore = "0.4"
nucleo = "0.5"
open = "5"
once_cell= "1.20"


crossterm = "0.28"
ratatui = "0.29"
tui-input = "0.11"


env_logger = {version = "0.11.6"}
log = {version = "0.4.25"}

[dependencies.lscolors]
version = "0.20"
default-features = false
features = ["crossterm"]

[features]
never = []
